/* Generated By:JJTree: Do not edit this line. ASTadditiveExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTadditiveExpression extends SimpleNode {
   String operator;
   
  public ASTadditiveExpression(int id) {
    super(id);
  }

  public ASTadditiveExpression(SPLParser p, int id) {
    super(p, id);
  }
  
  public void setOperator(String operator) {
     this.operator = operator;
  }
  
  public String getOperator() {
     return operator;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
     return super.toString() + ": " + operator;
  }
}
/* JavaCC - OriginalChecksum=e2fa24e090919b0bc761ec78f66dfca9 (do not edit this line) */
