/* Generated By:JJTree: Do not edit this line. ASTcomparisonExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTcomparisonExpression extends SimpleNode {
   String operator;
  public ASTcomparisonExpression(int id) {
    super(id);
  }

  public ASTcomparisonExpression(SPLParser p, int id) {
    super(p, id);
  }

  public void setOperator(String operator) {
     this.operator = operator;
  }
  
  public String getOperator() {
     return operator;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6593fbb61dcfa8dee5c0bccafb0f7e66 (do not edit this line) */
