/* Generated By:JJTree: Do not edit this line. ASTCompoundStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTCompoundStatement extends SimpleNode {
  public ASTCompoundStatement(int id) {
    super(id);
  }

  public ASTCompoundStatement(SPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dc3263adde231da7c9ab1395d04acc97 (do not edit this line) */
