/* Generated By:JJTree: Do not edit this line. ASTForEachStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public class ASTForEachStatement extends SimpleNode {
   private boolean holdability = false;

   public ASTForEachStatement(int id) {
      super(id);
   }

   public ASTForEachStatement(SPLParser p, int id) {
      super(p, id);
   }

   public void setHoldability(boolean holdability) {
      this.holdability = holdability;
   }

   public boolean isHoldable() {
      return holdability;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=da1ea877dc1acb3df81ec229afc57c8b (do not edit this line) */
