/* Generated By:JJTree: Do not edit this line. ASTIntoClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTIntoClause extends SimpleNode {
   private boolean resultSet;
   
  public ASTIntoClause(int id) {
    super(id);
  }

  public ASTIntoClause(SPLParser p, int id) {
    super(p, id);
  }
  
  public void setResultSet(boolean resultSet) {
     this.resultSet = resultSet;
  }
  
  public boolean isResultSet() {
     return resultSet;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=31a5fd5660299116a7eec1fe293c1c5d (do not edit this line) */
