/* Generated By:JJTree: Do not edit this line. ASTintervalParams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTintervalParams extends SimpleNode {
  public ASTintervalParams(int id) {
    super(id);
  }

  public ASTintervalParams(SPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a1e0615197f5c84763ef0cce188373ef (do not edit this line) */
