/* Generated By:JJTree: Do not edit this line. ASTintervalParam.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public class ASTintervalParam extends SimpleNode {
   private String param;

   public ASTintervalParam(int id) {
      super(id);
   }

   public ASTintervalParam(SPLParser p, int id) {
      super(p, id);
   }

   public void setParam(String param) {
      this.param = param;
   }

   public String getParam() {
      return param;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=bb81860300745228eda1cf908d59247f (do not edit this line) */
