/* Generated By:JJTree: Do not edit this line. ASTprepositionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTprepositionExpression extends SimpleNode {
   String operator;
   
  public ASTprepositionExpression(int id) {
    super(id);
  }

  public ASTprepositionExpression(SPLParser p, int id) {
    super(p, id);
  }

  public String getOperator() {
     return operator;
  }
  
  public void setOperator(String operator) {
     this.operator = operator;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c4229659e828042312b54a0a38caf36 (do not edit this line) */
