/* Generated By:JJTree: Do not edit this line. ASTProcedureDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public class ASTProcedureDeclaration extends SimpleNode {
   private String name;

   public ASTProcedureDeclaration(int id) {
      super(id);
   }

   public ASTProcedureDeclaration(SPLParser p, int id) {
      super(p, id);
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getName() {
      return name;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=9b12a2cc251d6e9ef7a5153f4f5dfb8f (do not edit this line) */
