/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public class ASTReturnStatement extends SimpleNode {
   private boolean resume = false;

   public ASTReturnStatement(int id) {
      super(id);
   }

   public ASTReturnStatement(SPLParser p, int id) {
      super(p, id);
   }

   public void setResume(boolean resume) {
      this.resume = resume;
   }

   public boolean isResume() {
      return resume;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=6f4300a24c111800e38d243dc6fbfda5 (do not edit this line) */
