/* Generated By:JJTree: Do not edit this line. ASTSetDebugFileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public
class ASTSetDebugFileStatement extends SimpleNode {
  public ASTSetDebugFileStatement(int id) {
    super(id);
  }

  public ASTSetDebugFileStatement(SPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8d3725a34f94c6bb467aa07abc981255 (do not edit this line) */
