/* Generated By:JJTree: Do not edit this line. ASTWorkStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xerxes500.transpiler.splparser.node;

import com.xerxes500.transpiler.splparser.*;

public class ASTTransactionStatement extends SimpleNode {
   private String command;

   public ASTTransactionStatement(int id) {
      super(id);
   }

   public ASTTransactionStatement(SPLParser p, int id) {
      super(p, id);
   }

   public void setCommand(String command) {
      this.command = command;
   }

   public String getCommand() {
      return command;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=e3a634731495e68591beff4d8e052717 (do not edit this line) */
