/* Generated By:JJTree: Do not edit this line. ASTAggregateFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTAggregateFunction extends SimpleNode {
   String name;

   public ASTAggregateFunction(int id) {
      super(id);
   }

   public ASTAggregateFunction(SPLParser p, int id) {
      super(p, id);
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getName() {
      return name;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=b6f6fb822d562773893217e4782ecc46 (do not edit this line) */
