/* Generated By:JJTree: Do not edit this line. ASTCreateTableStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTCreateTableStatement extends SimpleNode {
   String modifier;

   public ASTCreateTableStatement(int id) {
      super(id);
   }

   public ASTCreateTableStatement(SPLParser p, int id) {
      super(p, id);
   }

   public void setModifier(String modifier) {
      this.modifier = modifier;
   }

   public String getModifier() {
      return modifier;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=3861435f0d76b270e0842d3ae4c98e32 (do not edit this line) */
