/* Generated By:JJTree: Do not edit this line. ASTDeleteExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTDeleteExpression extends SimpleNode {
   private boolean whereClause = false;

   public ASTDeleteExpression(int id) {
      super(id);
   }

   public ASTDeleteExpression(SPLParser p, int id) {
      super(p, id);
   }

   /**
   * @return the whereClause
   */
   public boolean isWhereClause() {
      return whereClause;
   }

   /**
    * @param whereClause the whereClause to set
    */
   public void setWhereClause(boolean whereClause) {
      this.whereClause = whereClause;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=66a5653feb9091e7053dee02825036bf (do not edit this line) */
