/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTLiteral extends SimpleNode {
   protected String name;

   public ASTLiteral(int id) {
      super(id);
   }

   public ASTLiteral(SPLParser p, int id) {
      super(p, id);
   }

   public void setName(String name) {
      if (name.startsWith("'"))
         name = name.replaceAll("'", "\"");
      
      this.name = name;
   }

   public String getName() {
      return name;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
   
   public String toString() {
      return super.toString() + ": " + name;
   }
}
/* JavaCC - OriginalChecksum=67b1010a9f857ff6891f51eec81ac7df (do not edit this line) */
