/* Generated By:JJTree: Do not edit this line. ASTLockTableExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTLockTableExpression extends SimpleNode {
   private String mode;

   public ASTLockTableExpression(int id) {
      super(id);
   }

   public ASTLockTableExpression(SPLParser p, int id) {
      super(p, id);
   }

   public void setMode(String mode) {
      this.mode = mode;
   }

   public String getMode() {
      return mode;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=695c01ca0e44847c232c5a4a81e75efe (do not edit this line) */
