/* Generated By:JJTree: Do not edit this line. ASTmultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public
class ASTmultiplicativeExpression extends SimpleNode {
   String operator;
  public ASTmultiplicativeExpression(int id) {
    super(id);
  }

  public ASTmultiplicativeExpression(SPLParser p, int id) {
    super(p, id);
  }

  public void setOperator(String operator) {
     this.operator = operator;
  }
  
  public String getOperator() {
     return operator;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
     return super.toString() + ": " + operator;
  }

}
/* JavaCC - OriginalChecksum=eb3680906282fabd6fc80b1224201f3f (do not edit this line) */
