/* Generated By:JJTree: Do not edit this line. ASTOnExceptionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public
class ASTOnExceptionStatement extends SimpleNode {
   boolean open = false;
  public ASTOnExceptionStatement(int id) {
    super(id);
  }

  public ASTOnExceptionStatement(SPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public void setOpen(boolean open) {
     this.open = open;
  }
  
  public boolean isOpen() {
     return open;
  }
}
/* JavaCC - OriginalChecksum=0196782110a4204011db57a54ab8f82f (do not edit this line) */
