/* Generated By:JJTree: Do not edit this line. ASTOrderByExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTOrderByExpression extends SimpleNode {
   String modifier;

   public ASTOrderByExpression(int id) {
      super(id);
   }

   public ASTOrderByExpression(SPLParser p, int id) {
      super(p, id);
   }

   public void setModifier(String modifier) {
      this.modifier = modifier;
   }

   public String getModifier() {
      return modifier;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=aefd1cb1e35e6845856a63d347b0effb (do not edit this line) */
