/* Generated By:JJTree: Do not edit this line. ASTRaiseExceptionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public
class ASTRaiseExceptionStatement extends SimpleNode {
  public ASTRaiseExceptionStatement(int id) {
    super(id);
  }

  public ASTRaiseExceptionStatement(SPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95bc0376c265b7ff8c72b44d3631276a (do not edit this line) */
