/* Generated By:JJTree: Do not edit this line. ASTSelectExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTSelectExpression extends SimpleNode {
   private String  selectModifier = null;
   private boolean intoClause     = false;
   private boolean whereClause    = false;
   private boolean groupByClause  = false;
   private boolean orderByClause  = false;

   public ASTSelectExpression(int id) {
      super(id);
   }

   public ASTSelectExpression(SPLParser p, int id) {
      super(p, id);
   }

   public void setSelectModifier(String selectModifier) {
      this.selectModifier = selectModifier;
   }

   public String getSelectModifier() {
      return selectModifier;
   }

   public void setIntoClause(boolean intoClause) {
      this.intoClause = intoClause;
   }

   public boolean isIntoClause() {
      return intoClause;
   }

   public void setWhereClause(boolean whereClause) {
      this.whereClause = whereClause;
   }

   public boolean isWhereClause() {
      return whereClause;
   }

   public void setGroupByClause(boolean groupByClause) {
      this.groupByClause = groupByClause;
   }

   public boolean isGroupByClause() {
      return groupByClause;
   }

   public void setOrderByClause(boolean orderByClause) {
      this.orderByClause = orderByClause;
   }

   public boolean isOrderByClause() {
      return orderByClause;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=ba5f57710ef1e3a40115b950fe32c7e5 (do not edit this line) */
