/* Generated By:JJTree: Do not edit this line. ASTUpdateExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTUpdateExpression extends SimpleNode {
   private boolean whereClause = false;

   public ASTUpdateExpression(int id) {
      super(id);
   }

   public ASTUpdateExpression(SPLParser p, int id) {
      super(p, id);
   }

   public void setWhereClause(boolean whereClause) {
      this.whereClause = whereClause;
   }

   public boolean isWhereClause() {
      return whereClause;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=af89c6443f004077a31801c5dffce917 (do not edit this line) */
