/* Generated By:JJTree: Do not edit this line. ASTunaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dontexist.morals.splparser.node;

import com.dontexist.morals.splparser.*;

public class ASTunaryExpression extends SimpleNode {
   String operator;

   /**
    * @return the operator
    */
   public String getOperator() {
      return operator;
   }

   /**
    * @param operator the operator to set
    */
   public void setOperator(String operator) {
      this.operator = operator;
   }

   public ASTunaryExpression(int id) {
      super(id);
   }

   public ASTunaryExpression(SPLParser p, int id) {
      super(p, id);
   }

   /** Accept the visitor. **/
   public Object jjtAccept(SPLParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=6f1670bdbf64c9f44a2a8a36ebf4a845 (do not edit this line) */
